# Generated by Django 3.1.5 on 2021-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='host',
            name='host_avatar_image',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=245, unique=True),
        ),
    ]
