# Generated by Django 3.1.5 on 2021-01-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_method',
        ),
    ]
