# Generated by Django 3.1.5 on 2021-01-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(max_length=20)),
                ('people', models.IntegerField()),
                ('day', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.packageprice')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.timeprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=245)),
                ('purpose', models.CharField(max_length=30)),
                ('reservation_request', models.CharField(max_length=500)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_informations',
            },
        ),
    ]
