# Generated by Django 3.1.5 on 2021-01-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinformation',
            name='email',
            field=models.EmailField(max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name='reservationinformation',
            name='purpose',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reservationinformation',
            name='reservation_request',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
