# Generated by Django 3.1.5 on 2021-01-18 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
