# Generated by Django 3.1.5 on 2021-01-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationinformation',
            name='price',
            field=models.IntegerField(default=18000),
            preserve_default=False,
        ),
    ]
