# Generated by Django 3.1.5 on 2021-01-20 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationinformation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
