# Generated by Django 3.1.5 on 2021-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210118_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(default='package', max_length=20),
            preserve_default=False,
        ),
    ]
