# Generated by Django 3.1.5 on 2021-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20210120_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_type',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
