# Generated by Django 3.1.5 on 2021-01-23 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210121_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='day',
            new_name='end_day',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
