# Generated by Django 3.1.5 on 2021-01-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20210123_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_day',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_day',
        ),
    ]
