# Generated by Django 3.1.5 on 2021-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='locationd',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='breakday',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detailfacility',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='space',
            name='main_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
