# Generated by Django 3.1.5 on 2021-01-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeprice',
            name='time_reservation_type',
        ),
        migrations.AddField(
            model_name='timeprice',
            name='people',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
