# Generated by Django 3.1.5 on 2021-01-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='close_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='space',
            name='open_time',
            field=models.CharField(max_length=10),
        ),
    ]
