# Generated by Django 3.1.5 on 2021-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20210113_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='lng',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='detailspace',
            name='image',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='space',
            name='close_time',
            field=models.TimeField(default=24),
        ),
        migrations.AlterField(
            model_name='space',
            name='email',
            field=models.EmailField(max_length=245),
        ),
        migrations.AlterField(
            model_name='space',
            name='main_image',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='space',
            name='open_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='space',
            name='site_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='subimage',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
