# Generated by Django 3.1.5 on 2021-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20210120_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspace',
            name='max_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detailspace',
            name='min_people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detailspace',
            name='min_reservation_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detailspace',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='excess_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timeprice',
            name='excess_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timeprice',
            name='people',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='timeprice',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
